name: Setando environment de produção

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  web-deploy:
    name: 🎉 Test Code and Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4.13'
    - name: Copy ENV for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      working-directory: api/ecoleta-api
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: api/ecoleta-api
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: api/ecoleta-api
    - name: Create DB and schemas
      run: touch database/database.sqlite
      working-directory: api/ecoleta-api
    - name: Generate key
      run: php artisan key:generate
      working-directory: api/ecoleta-api
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
      working-directory: api/ecoleta-api

    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: api/ecoleta-api

    environment:
      name: production
      url: https://ufpi-ecoleta.herokuapp.com

  build:
    name: 🎉 Install and build app expo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/ecoleta
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build --platform all --non-interactive