name: Setando environment de produção

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: 🎉 Environment to Heroku
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ufpi-ecoleta.herokuapp.com
    steps:
      - uses: actions/checkout@v2