name: Setando environment de produção

on:
  push:
    branches:
      - dev
      - main

jobs:
  web-deploy:
    name: 🎉 Test Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4.13'
    - name: Copy ENV for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      working-directory: api/ecoleta-api
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: api/ecoleta-api
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: api/ecoleta-api
    - name: Create DB and schemas
      run: touch database/database.sqlite
      working-directory: api/ecoleta-api
    - name: Generate key
      run: php artisan key:generate
      working-directory: api/ecoleta-api
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
      working-directory: api/ecoleta-api

    # - uses: actions/checkout@v2
    # - uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
    #     heroku_email: ${{ secrets.HEROKU_EMAIL }}

    environment:
      name: production
      url: https://ufpi-ecoleta.herokuapp.com